# Generated by Django 3.2.4 on 2022-05-23 19:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='avatar'),
        ),
    ]
