version: "3.8"

services:
    django:
        build: .
        container_name: edu
        command: bash .sh

        volumes:
            - .:/usr/src/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
