# Generated by Django 3.2.13 on 2022-05-10 14:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
